- name: Install dependencies
        run: pip install .

      - name: Create Google Credentials File
        # This takes your Secret string and writes it to the file the script expects
        run: |
          mkdir -p credentials
          echo '${{ secrets.GOOGLE_CREDENTIALS }}' > credentials/client_secret.json

      - name: Run Sync Script
        env:
          USER1_GARMIN_EMAIL: ${{ secrets.GARMIN_EMAIL }}
          USER1_GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
          USER1_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          # Tell the script where to find the file we just created
          GOOGLE_CLIENT_SECRET_PATH: "credentials/client_secret.json"
        # We use 'python -m src.main' to ensure we access the 'cli-sync' command
        run: python -m src.main cli-sync --start-date 2026-03-01 --profile USER1 --output-type sheets
